homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

hello:
    path: /hello/{name}
    controller: App\Controller\DefaultController::hello
    defaults: { name: 'tout le monde' } # rend le param√®tre du "path" optionnel

article:
    path: /{_locale}/article/{id}.{_format}
    controller: App\Controller\DefaultController::article
    requirements: { id: \d+, _locale: '[a-z]{2}(_[A-Z]{2})?', _format: html|json }
